var Activity = {
	ZERO: 0,
	INICIO: 4,
	ANALISAR_CNPJ: 8,
	FIM_CANCELADO: 14,
	ANALISAR_REPROVACAO_CANAIS: 17,
	ANALISAR_REPROVACAO_FRANQUIA: 42,
	INFORMAR_CODIGO_UNIDADE: 61,
	AGUARDAR_ENCERRAMENTO_CHAMADOS: 69,
	INCLUIR_CLAUSULAS: 98
}
